### PR TITLE
Add support for 7.2.0

### PR DESCRIPTION
**Pull request by codezomb**
This adds support for ES v7.2.0 per instructions in the #kubedb slack channel.

### CODE REVIEW

**Comment by tamalsaha** [comment]
@hossainemruz / @the-redback can you take a look?

**Comment by botzill** [comment]
Any updates on this?

**Comment by the-redback** [comment]
I found some issues [breaking changes] while testing this PR.

- `http.enabled` was deprecated and removed in 7.2.0. So, need to remove http.enabled options. xref: [7.0 breaking changes](https://www.elastic.co/guide/en/elasticsearch/reference/7.2/breaking-changes-7.0.html#remove-http-enabled)
- `discovery.zen.ping.unicast.hosts` got new name `discovery.seed_hosts`. xref: [official blog post](https://www.elastic.co/blog/a-new-era-for-cluster-coordination-in-elasticsearch)
- `discovery.zen.minimum_master_nodes` is deprecated. new `cluster.initial_master_nodes` must be set to perform cluster bootstrapping. May be a headless service is needed here. xref: [7.0 breaking changes](https://www.elastic.co/guide/en/elasticsearch/reference/7.2/breaking-changes-7.0.html#_cluster_bootstrapping_is_required_if_discovery_is_configured)

Resources: 
- [A new era for cluster coordination in Elasticsearch](https://www.elastic.co/blog/a-new-era-for-cluster-coordination-in-elasticsearch)

**Comment by etiennecl** [comment]
Any news on this?

**Comment by tamalsaha** [comment]
@etiennecl , @the-redback and I are working on getting the v0.13.0-rc.0 release out. @the-redback found some issues with the new ES version that requires changes in the operator. He is going to work on that after the rd release is out. This has to be part of the next release v0.14.0 which we hope to cut in short order. Sorry about the delay.

**Comment by etiennecl** [comment]
That's really nice to read! I've just seen that v0.13.0-rc0 has been released, do you have an ETA for the v0.14.0 ?

**Comment by botzill** [comment]
Hi.

Is 7.2.0 supported in v0.13.0-rc0?

I just don't see the version here: https://kubedb.com/docs/v0.13.0-rc.0/guides/elasticsearch/ 

Thx

**Comment by the-redback** [comment]
@botzill, It's going to be a part of `0.14.0` release with other updated db versions. 

@etiennecl , Actually it's hard to estimate an ETA for releases. But, we will try to release it within a month. But, things often get out of hand. :(

**Comment by the-redback** [comment]
So, there were couple of undocumented breaking changes from searchguard end. I posted on their forum and got their help.  https://forum.search-guard.com/t/searchguard-36-0-0-actiongroup-example-fails-config-validation-in-search-guard-7-tools-sgadmin-sh/1642/7

I am going to add a Followup PR to cover the changes from operator end.

**Comment by botzill** [comment]
Great, I see the latest version is `7.3.2`, will this as well be supported?

**Pull request merged**
